import Link from "next/link";
import { desc, eq } from "drizzle-orm";
import { requireChatGPTUser } from "../../chatgpt-auth";
import { getDb } from "../../../db";
import { jobTracks } from "../../../db/schema";
import { createJobTrack, removeJobTrack, statuses, updateJobTrack } from "./actions";

export const dynamic = "force-dynamic";
const input = "mt-2 block w-full rounded-xl border border-slate-300 bg-white px-4 py-3 outline-none focus:border-red-500";
export default async function JobsPage() {
  const user = await requireChatGPTUser("/workspace/jobs");
  const items = await getDb().select().from(jobTracks).where(eq(jobTracks.ownerId, user.userId)).orderBy(desc(jobTracks.updatedAt));
  return <main className="min-h-screen bg-[#f2f5f7] px-5 py-12 text-[#10273c]"><div className="mx-auto max-w-5xl"><Link href="/workspace" className="text-sm font-semibold text-red-700">← Workspace</Link><header className="mt-8 rounded-3xl bg-[#10273c] p-8 text-white md:p-12"><p className="text-xs font-bold uppercase tracking-[.2em] text-red-300">DigitalBurj Jobs</p><h1 className="mt-4 text-4xl font-bold tracking-tight">Your opportunity tracker</h1><p className="mt-4 max-w-2xl text-slate-300">Keep a private record of roles you find and steps you take. Saving or updating a role here does not apply to an employer or confirm an interview or offer.</p></header>
    <section className="mt-8 rounded-2xl border border-slate-200 bg-white p-6 md:p-8"><h2 className="text-2xl font-bold">Track an opportunity</h2><form action={createJobTrack} className="mt-5 grid gap-4 md:grid-cols-2"><label className="text-sm font-semibold">Role title<input name="roleTitle" required maxLength={120} className={input}/></label><label className="text-sm font-semibold">Employer<input name="employer" required maxLength={120} className={input}/></label><label className="text-sm font-semibold md:col-span-2">Job posting URL (optional)<input name="sourceUrl" type="url" maxLength={500} placeholder="https://…" className={input}/></label><label className="text-sm font-semibold md:col-span-2">Private notes<textarea name="notes" maxLength={1000} rows={3} className={input}/></label><button className="w-fit rounded-full bg-[#e31b23] px-7 py-3 font-bold text-white transition hover:bg-red-700">Save opportunity</button></form></section>
    <section className="mt-8"><h2 className="text-2xl font-bold">Saved opportunities ({items.length})</h2><div className="mt-4 grid gap-4">{items.length ? items.map(item=><article key={item.id} className="rounded-2xl border border-slate-200 bg-white p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="text-xl font-bold">{item.roleTitle}</h3><p className="mt-1 text-slate-600">{item.employer}</p></div><span className="rounded-full bg-slate-100 px-4 py-1 text-xs font-semibold">{item.status}</span></div>{item.sourceUrl && <a href={item.sourceUrl} target="_blank" rel="noopener noreferrer" className="mt-4 inline-block text-sm font-semibold text-red-700 underline">View original posting ↗</a>}{item.notes && <p className="mt-4 whitespace-pre-wrap text-sm text-slate-600">{item.notes}</p>}<div className="mt-5 flex flex-wrap items-end gap-5 border-t border-slate-100 pt-5"><form action={updateJobTrack} className="flex flex-wrap items-end gap-3"><input type="hidden" name="id" value={item.id}/><label className="text-sm font-semibold">Personal status<select name="status" defaultValue={item.status} className={input}>{statuses.map(x=><option key={x}>{x}</option>)}</select></label><button className="rounded-full bg-[#10273c] px-5 py-3 text-sm font-bold text-white">Update</button></form><form action={removeJobTrack}><input type="hidden" name="id" value={item.id}/><button className="py-3 text-sm font-semibold text-red-700">Remove</button></form></div></article>) : <p className="rounded-2xl border border-dashed border-slate-300 bg-white p-8 text-slate-600">Your tracker is empty. Add a role above to begin.</p>}</div></section>
  </div></main>;
}
