"use client";
import { useState } from "react";
import Link from "next/link";
import { ArrowUpRight, AppWindow, MessageCircle, Smartphone, Code2, Workflow, CheckCircle2 } from "lucide-react";

const channels=[
  {id:"web",label:"Web app",title:"Your work has a place to live.",body:"Move from the first enquiry to a private workspace for your messages, files, and Academy progress.",action:"Open the workspace",href:"/workspace",Icon:AppWindow,steps:["Explore a service","Send a brief","Follow the work"]},
  {id:"mobile",label:"On your phone",title:"Pick up where you left off.",body:"The same DigitalBurj workspace works in a mobile browser, so your next step is always close.",action:"Explore on mobile",href:"/get-started",Icon:Smartphone,steps:["Choose your goal","Open your workspace","Continue on any screen"]},
  {id:"whatsapp",label:"WhatsApp",title:"Start with a conversation.",body:"Check the official WhatsApp channel or use a structured enquiry when the business number is not yet connected.",action:"Check WhatsApp",href:"/connect/whatsapp",Icon:MessageCircle,steps:["Describe the need","Find the right team","Continue with clarity"]},
] as const;
export function ExperienceSwitch(){
  const [selected,setSelected]=useState<(typeof channels)[number]["id"]>("web");
  const item=channels.find(x=>x.id===selected)!;
  return <section className="experience-section section-pad" id="ways-to-connect" aria-labelledby="experience-title"><div className="shell"><div className="section-heading" data-reveal><div><span className="eyebrow eyebrow-light">05 / Work with us</span><h2 className="display-title" id="experience-title">A clearer path from <span className="serif-accent">idea to action.</span></h2></div><p>Choose the channel that suits you. Every route leads to a useful next step.</p></div><div className="experience-layout"><div className="experience-content"><div className="experience-tabs" role="tablist" aria-label="Ways to connect with DigitalBurj">{channels.map(x=><button key={x.id} type="button" role="tab" id={`channel-${x.id}`} aria-selected={selected===x.id} aria-controls="channel-panel" onClick={()=>setSelected(x.id)} className={selected===x.id?"active":""}><x.Icon size={18}/>{x.label}</button>)}</div><div className="experience-copy" key={item.id} role="tabpanel" id="channel-panel" aria-labelledby={`channel-${item.id}`}><span className="experience-index">DIGITALBURJ / {item.label.toUpperCase()}</span><h3>{item.title}</h3><p>{item.body}</p><Link href={item.href} className="btn btn-red">{item.action}<ArrowUpRight size={18}/></Link></div><div className="experience-secondary"><Link href="/workspace/intake?service=studio">Plan a web or mobile product <ArrowUpRight size={16}/></Link><Link href="/workspace/intake?service=business">Improve a business workflow <ArrowUpRight size={16}/></Link></div></div><div className="experience-device" aria-hidden="true"><div className="device-chrome"><span/><span/><span/><strong>DIGITALBURJ / WORKSPACE</strong></div><div className="device-body"><div className="device-status"><span className="device-orbit"><Code2 size={27}/></span><span>One connected workflow<small>From first step to visible progress</small></span></div><div className="device-flow">{item.steps.map((step,i)=><div key={step} className="device-flow-row" style={{animationDelay:`${i*120}ms`}}><span>0{i+1}</span><strong>{step}</strong>{i===2?<CheckCircle2 size={19}/>:<Workflow size={19}/>}</div>)}</div><div className="device-bottom"><span>ACADEMY</span><span>STUDIO</span><span>BUSINESS AI</span></div></div></div></div></div></section>;
}
