import Link from "next/link";
import { ArrowDown, ArrowUpRight, MoveUpRight } from "lucide-react";
import { SiteHeader, SiteFooter, divisions } from "./site-shell";
import { MotionLayer } from "./motion-layer";
import { MagneticLink } from "./magnetic-link";
import { HeroCarousel } from "./hero-carousel";
import { StoryShowcase } from "./story-showcase";
import { ExperienceSwitch } from "./experience-switch";
export default function Home() {
  return <main className="public-site"><MotionLayer/><SiteHeader/>
    <section className="home-hero"><HeroCarousel frames={[{src:"/brand/hero-digitalburj-v2.webp",label:"A connected future"},{src:"/brand/hero-studio-generated.webp",label:"Build what matters"},{src:"/brand/hero-academy-generated.webp",label:"Learn by doing"},{src:"/brand/hero-business-generated.webp",label:"Improve the work"},{src:"/brand/hero-talent-generated.webp",label:"Grow together"},{src:"/brand/hero-jobs-generated.webp",label:"Find opportunity"}]}/><div className="home-hero-shade"/><div className="shell home-hero-inner"><div className="hero-content"><span className="eyebrow eyebrow-light"><span className="eyebrow-line"/> A connected digital ecosystem</span><h1>Learn. Build.<br/><em>Transform.</em></h1><p>Develop real capability. Engineer better digital products. Rethink how business works.</p><div className="hero-actions"><MagneticLink href="/get-started" className="btn-red">Find your path</MagneticLink><Link href="/ecosystem" className="btn btn-outline-light">Explore DigitalBurj <ArrowUpRight size={19}/></Link></div></div><a href="#explore" className="scroll-cue">Scroll to explore <ArrowDown size={17}/></a></div></section>
    <section id="explore" className="intro-section section-pad"><div className="shell intro-grid"><div data-reveal><span className="eyebrow">01 / The idea</span><h2 className="display-title">Progress is <span className="serif-accent">built</span> together.</h2></div><div className="intro-side" data-reveal><p>DigitalBurj brings learning, engineering, business improvement and professional opportunity into one connected experience. Start with the challenge in front of you. Move forward with work you can show.</p><Link href="/company" className="text-link">Meet DigitalBurj <ArrowUpRight size={19}/></Link></div></div></section>
    <section className="division-section section-pad"><div className="shell"><div className="section-heading" data-reveal><div><span className="eyebrow">02 / The ecosystem</span><h2 className="display-title">One company. <span className="serif-accent">Three engines.</span></h2></div><p>Learn what matters. Build what deserves to exist. Improve what can work better.</p></div><div className="division-grid">{divisions.slice(0,3).map((d,i)=><Link href={`/${d.slug}`} className={`division-card division-card-${d.slug}`} key={d.slug} data-reveal><div className="division-top"><span>0{i+1} / {d.label}</span><span className="round-arrow"><ArrowUpRight size={22}/></span></div><div className="division-card-visual"><span className="division-card-photo" style={{backgroundImage:`url('${["/brand/system-academy.webp","/brand/system-studio.webp","/brand/system-business.webp"][i]}')`}}/><span className="division-card-visual-label">DIGITALBURJ / {d.name.toUpperCase()}</span></div><div className="division-bottom"><h3>{d.name}</h3><p>{d.description}</p></div></Link>)}</div><div className="support-row"><Link href="/talent"><span>04 / VERIFIED TALENT</span><strong>Capability you can show.</strong><ArrowUpRight size={21}/></Link><Link href="/jobs"><span>05 / JOBS</span><strong>Opportunity with a clearer path.</strong><ArrowUpRight size={21}/></Link></div></div></section>
    <StoryShowcase/>
    <ExperienceSwitch/>
    <section className="feature-section"><div className="feature-photo" role="img" aria-label="DigitalBurj learners collaborating on a project"/><div className="feature-copy" data-reveal><span className="eyebrow eyebrow-light">06 / Learn by doing</span><h2>Skills that stand up <span className="serif-accent">in the real world.</span></h2><p>At DigitalBurj Academy, learning leads to practical work, useful feedback and a clearer picture of what you can do.</p><Link href="/academy" className="btn btn-red">Explore the Academy <ArrowUpRight size={19}/></Link></div></section>
    <section className="approach-section section-pad"><div className="shell"><div className="section-heading" data-reveal><div><span className="eyebrow">07 / Our approach</span><h2 className="display-title">Ideas need <span className="serif-accent">evidence.</span></h2></div><p>Clarity and craft at every step.</p></div><div className="approach-grid">{[{n:"01",title:"Understand",body:"Begin with the real problem and the people it affects."},{n:"02",title:"Make",body:"Design, test and build something useful."},{n:"03",title:"Prove",body:"Measure the result and show the work behind it."}].map(x=><div className="approach-item" key={x.n} data-reveal><span className="approach-ring"><b>{x.n}</b></span><h3>{x.title}</h3><p>{x.body}</p><MoveUpRight size={23}/></div>)}</div></div></section>
    <section className="final-cta"><div className="shell final-cta-inner" data-reveal><span className="eyebrow eyebrow-light">Your next chapter</span><h2>Let&apos;s build<br/><em>what&apos;s possible.</em></h2><Link href="/get-started" className="btn btn-white">Start with your goal <ArrowUpRight size={19}/></Link></div></section><SiteFooter/></main>;
}
