import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowUpRight } from "lucide-react";
import { SiteHeader, SiteFooter } from "../site-shell";
import { HeroCarousel } from "../hero-carousel";
import { MotionLayer } from "../motion-layer";
const content:Record<string,{eyebrow:string;title:string;intro:string;image:string;pillars:string[];path:string[];cta:string;note?:string}> = {
  studio:{eyebrow:"Product & engineering",title:"Good ideas deserve better execution.",intro:"From the first business problem to product discovery, engineering, quality assurance and measured delivery.",image:"/brand/hero-studio-generated.webp",pillars:["Discovery & validation","Software, SaaS and mobile","Enterprise apps & integrations","Quality & delivery assurance"],path:["Submit an enquiry","Discuss the problem","Validate feasibility","Decide what to build","Scope and deliver"],cta:"Start a project enquiry"},
  business:{eyebrow:"Business transformation & AI",title:"Make better work possible.",intro:"Understand how work happens today, find the operational leak, design a better workflow and apply automation where it helps.",image:"/brand/hero-business-generated.webp",pillars:["Operational diagnosis","Process improvement","CRM & systems integration","Controlled AI automation"],path:["Consult","Observe operations","Diagnose and measure","Approve a solution","Implement and evaluate"],cta:"Request a consultation",note:"Consequential automation requires human oversight."},
  talent:{eyebrow:"Evidence-backed capability",title:"Let your work speak for itself.",intro:"A professional profile that distinguishes declared skills, assessed work and independently verified capability.",image:"/brand/hero-talent-generated.webp",pillars:["Professional profile","Skills & projects","Evidence and assessments","Capability passport & privacy"],path:["Build a profile","Add experience","Attach evidence","Request review","Control visibility"],cta:"Open Talent workspace",note:"Your Academy or client work never becomes public evidence automatically."},
  jobs:{eyebrow:"Employment platform",title:"Opportunity meets capability.",intro:"A structured path for candidates and employers, with applications and hiring decisions kept transparent.",image:"/brand/hero-jobs-generated.webp",pillars:["Find opportunities","Track applications","Employer recruitment","Interviews & offers"],path:["Explore a listing","Apply","Employer review","Interview or assessment","Hiring decision"],cta:"Open Jobs workspace",note:"Hiring decisions remain with employers. DigitalBurj does not guarantee jobs or visas."},
};
const links:Record<string,string>={studio:"/workspace/intake?service=studio",business:"/workspace/intake?service=business",talent:"/workspace/talent",jobs:"/workspace/jobs"};
export function generateStaticParams(){return Object.keys(content).map(division=>({division}));}
export default async function DivisionPage({params}:{params:Promise<{division:string}>}){
  const {division}=await params;const d=content[division];if(!d)notFound();
  return <main className="public-site"><MotionLayer/><SiteHeader/><section className="page-hero"><HeroCarousel frames={[{src:d.image,label:d.eyebrow},{src:"/brand/hero-digitalburj-v2.webp",label:"DigitalBurj"}]}/><div className="shell page-hero-content"><span className="eyebrow eyebrow-light">DigitalBurj / {d.eyebrow}</span><h1>{d.title}</h1><p>{d.intro}</p><Link href={links[division]} className="btn btn-red mt-9">{d.cta}<ArrowUpRight size={18}/></Link></div></section><section className="shell section-pad"><span className="eyebrow">01 / What we do</span><h2 className="display-title max-w-3xl">Built around your <span className="serif-accent">challenge.</span></h2><div className="editorial-grid mt-12">{d.pillars.map((x,i)=><div className="editorial-card service-card" key={x} data-reveal><div className="service-card-top"><span className="eyebrow">0{i+1}</span><div className="service-thumbnail" style={{backgroundImage:`url('${["/brand/system-academy.webp","/brand/system-studio.webp","/brand/system-business.webp","/brand/strategy.jpg"][i]}')`}} aria-hidden="true"/></div><h3>{x}</h3></div>)}</div></section><section className="section-pad bg-[#f1f4f6]"><div className="shell"><span className="eyebrow">02 / The process</span><h2 className="display-title">From question to <span className="serif-accent">outcome.</span></h2><div className="process-grid mt-12">{d.path.map((x,i)=><div key={x} className="process-card"><span className="eyebrow">0{i+1}</span><h3>{x}</h3></div>)}</div>{d.note&&<p className="mt-8 max-w-2xl border-l-4 border-[#e10613] pl-5 leading-7 text-[#526577]">{d.note}</p>}</div></section><section className="final-cta"><div className="shell final-cta-inner"><span className="eyebrow eyebrow-light">Take the next step</span><h2>Let&apos;s get <em>started.</em></h2><Link href={links[division]} className="btn btn-white">{d.cta}<ArrowUpRight size={18}/></Link></div></section><SiteFooter/></main>;
}
