// Help center articles (blueprint Domain 10 §5 categories, Domain 11 §2 page template).
export type Article = { slug: string; category: string; title: string; purpose: string; audience: string; steps: string[]; permissions: string; result: string; troubleshooting: string[] };

export const ARTICLES: Article[] = [
  { slug: "switch-organization", category: "Account & Security", title: "Work in a personal or organization context", purpose: "Choose whose records you are working with.", audience: "Everyone with a workspace", steps: ["Open Workspace → Organizations.", "Choose Switch here on the organization, or on Personal workspace.", "The sidebar shows the current context; every page now shows only that context's records."], permissions: "Active membership of the organization.", result: "Projects, files, messages, invoices and search results change to the selected context.", troubleshooting: ["If an organization is missing, accept its invitation first (sign in with the invited email).", "If you were removed, the app returns you to your personal workspace."] },
  { slug: "roles", category: "Account & Security", title: "Organization roles and what they can do", purpose: "Understand who can approve, hire, see invoices and manage members.", audience: "Organization owners and admins", steps: ["Owners and admins invite members and choose a role.", "Owner: everything. Admin: manage members (not owners), approve, developers. Billing Manager: invoices. Studio Client Owner and Business AI Owner: approve milestones, change requests and automations. Recruiter: manage roles and applications. Hiring Manager: also approve offers. Guest: read-only."], permissions: "Owner or admin to change roles; only an owner grants admin.", result: "Approvals and pages appear only for roles that can act on them.", troubleshooting: ["An organization must always keep one owner.", "Every role change is recorded in the Security center."] },
  { slug: "export-data", category: "Account & Security", title: "Download or delete your data", purpose: "Exercise access and deletion requests.", audience: "Everyone", steps: ["Workspace → Account & privacy → Download my data (JSON).", "To delete, write a reason under Delete my account; a privacy ticket opens and a person handles each step."], permissions: "Signed in.", result: "A JSON file of your records, or a tracked deletion ticket.", troubleshooting: ["Invoices and audit records may need to be retained for legal reasons; the team explains what is kept."] },
  { slug: "academy-missions", category: "Academy", title: "Submit a mission and get it assessed", purpose: "Turn learning into assessed evidence.", audience: "Learners", steps: ["Save a unit from the catalogue.", "Open a published mission, read the scenario, rubric and required output.", "Submit your work and an optional https link to an artifact.", "An assessor scores each rubric criterion 0–4 and decides: passed, revision required or failed.", "If revision is required, resubmit within the attempt limit."], permissions: "Signed in.", result: "A passed mission, ready for independent verification.", troubleshooting: ["A pass needs at least 2/4 on every criterion.", "You cannot have two active submissions for one mission."] },
  { slug: "academy-credentials", category: "Academy", title: "Independent verification and credentials", purpose: "Get a credential employers can check.", audience: "Learners with a passed mission", steps: ["On the passed mission choose Request independent verification.", "A verifier who did not assess your work reviews the evidence.", "If verified, a credential ID (DBC-XXXXXXXX) and public verification link are issued.", "Optionally add it to your Talent profile from My credentials."], permissions: "The submission must be passed.", result: "A verifiable credential at /verify/<ID>.", troubleshooting: ["If verification is declined, the note explains why; you can take the mission again."] },
  { slug: "studio-delivery", category: "Studio", title: "From enquiry to release with Studio", purpose: "Follow a Studio project end to end.", audience: "Studio clients", steps: ["Send an enquiry, open a working brief and add discovery entries.", "Request discovery; the team qualifies it and records BUILD, RESHAPE or STOP with the evidence.", "Approve each milestone in your approval center.", "Request changes; you approve the quoted impact before anything changes.", "Track release readiness: QA, security, accessibility, backups, rollback and client approval."], permissions: "Personal projects: you. Organization projects: owner, admin or Studio Client Owner approve.", result: "Every decision and approval is on the project page and in its history.", troubleshooting: ["Submitting a brief is not an approval, quotation or contract."] },
  { slug: "business-ai-automation", category: "Business AI", title: "How automations are governed", purpose: "Know what needs your approval.", audience: "Business AI clients", steps: ["The team diagnoses the process and records baselines as measured or estimated.", "Each automation has a risk level: low, medium, high or critical.", "You approve every automation design before it is built.", "High-risk automations also need your approval to go live.", "Critical-risk work never runs autonomously; it stays a controlled human process."], permissions: "Owner, admin or Business AI Owner approve for organizations.", result: "Before/after metrics and each automation's state are on the engagement page.", troubleshooting: ["If an automation fails, you are notified immediately and it returns to building."] },
  { slug: "talent-passport", category: "Talent", title: "Your Capability Passport and privacy", purpose: "Share evidence on your terms.", audience: "Professionals", steps: ["Add evidence as declared.", "Request verification; a verifier may verify, reject or ask for more information.", "In the privacy center choose private, verified employers or public, and whether you appear in employer search.", "Set each evidence item's visibility separately."], permissions: "Signed in.", result: "A passport that shows verified and declared items separately.", troubleshooting: ["Academy work never becomes Talent evidence unless you add it.", "Private profiles do not exist publicly at all."] },
  { slug: "jobs-apply", category: "Jobs", title: "Apply and track an application", purpose: "Apply with a structured application.", audience: "Candidates", steps: ["Browse roles on the jobs board and open one.", "Sign in, write a cover note and answer the employer's questions.", "Optionally share your Capability Passport and consent to an assessment.", "Track each stage under Workspace → Jobs → My applications, and accept or decline offers there."], permissions: "Signed in.", result: "The employer sees your application; you see every stage change.", troubleshooting: ["Hiring decisions remain with employers. DigitalBurj does not guarantee jobs or visas."] },
  { slug: "jobs-hire", category: "Jobs", title: "Hire with DigitalBurj", purpose: "Publish roles and run a transparent pipeline.", audience: "Employers", steps: ["Request employer verification from Organizations.", "Draft a role in the employer console; publish once verified.", "Move candidates through review, shortlist, assessment, interview and final review.", "Schedule interviews and record feedback.", "Submit an offer; an owner or hiring manager approves before the candidate sees it."], permissions: "Owner, admin, recruiter or hiring manager; offers are approved by owner or hiring manager.", result: "Reports for time to first review, time to hire and offer acceptance.", troubleshooting: ["Publishing is disabled until DigitalBurj verifies the organization."] },
  { slug: "billing", category: "Billing", title: "Invoices and payments", purpose: "See and pay what DigitalBurj invoiced.", audience: "Customers and billing managers", steps: ["Open Workspace → Billing.", "Pay by bank transfer using the details on the invoice.", "Finance records the payment and you are notified."], permissions: "Individuals see their own; organizations: owner, admin and billing manager.", result: "Outstanding and paid invoices in one place.", troubleshooting: ["Online card payment is not connected yet."] },
  { slug: "api-webhooks", category: "Integrations", title: "API keys and webhooks", purpose: "Connect your systems.", audience: "Organization owners and admins", steps: ["Switch to the organization and open Developers.", "Create an API key with only the scopes you need; copy it once.", "Add a webhook endpoint (https) and the events to receive.", "Verify each delivery's x-digitalburj-signature header (HMAC-SHA256 of the body)."], permissions: "Owner or admin.", result: "Scoped API access and signed event delivery.", troubleshooting: ["Deliveries time out after 4 seconds; check the delivery log.", "Revoked keys stop working immediately."] },
];
export const CATEGORIES = [...new Set(ARTICLES.map(a => a.category))];
