import Link from "next/link";
import { ArrowUpRight } from "lucide-react";
import { academyCourses, academyStages } from "../academy-data";
import { SiteHeader, SiteFooter } from "../site-shell";
import { HeroCarousel } from "../hero-carousel";
import { MotionLayer } from "../motion-layer";
const featured=academyCourses.filter(c=>["DB-00","DB-01","DB-02","DB-03","PC-AD01","PC-AC01","PC-LG01"].includes(c.code));
export default function Academy(){
  return <main className="public-site academy-site"><MotionLayer/><SiteHeader/><section className="page-hero academy-hero"><HeroCarousel frames={[{src:"/brand/hero-academy-generated.webp",label:"The Academy"},{src:"/brand/academy.jpg",label:"Learning space"},{src:"/brand/workshop.jpg",label:"Practical learning"},{src:"/brand/hero-digitalburj-v2.webp",label:"Connected learning"}]}/><div className="shell page-hero-content"><span className="eyebrow eyebrow-light">DigitalBurj / Academy</span><h1>Learn by doing.<br/><span className="serif-accent">Grow with proof.</span></h1><p>Build useful skills through practical work, reflection and clear evidence of what you can do.</p><div className="hero-actions"><Link href="/academy/catalogue" className="btn btn-red">Explore the catalogue <ArrowUpRight size={18}/></Link><Link href="/workspace/academy" className="btn btn-outline-light">My learning <ArrowUpRight size={18}/></Link></div></div></section>
    <section className="shell section-pad"><div className="intro-grid"><div><span className="eyebrow">01 / The learning model</span><h2 className="display-title">The work is <span className="serif-accent">the lesson.</span></h2></div><div className="intro-side"><p>Start with a brief. Investigate, build, break, fix and test. Then explain your decisions and keep a record of the evidence. Independent verification remains a separate review.</p><Link href="/academy/tools" className="text-link">Explore the tool library <ArrowUpRight size={19}/></Link></div></div><div className="academy-stage-grid">{academyStages.map((stage,i)=><div key={stage} className="academy-stage"><span>{String(i+1).padStart(2,"0")}</span><strong>{stage}</strong></div>)}</div></section>
    <section className="division-section section-pad"><div className="shell"><div className="section-heading"><div><span className="eyebrow">02 / The catalogue</span><h2 className="display-title">Find your <span className="serif-accent">starting point.</span></h2></div><Link href="/academy/catalogue" className="text-link">View all {academyCourses.length} units <ArrowUpRight size={19}/></Link></div><div className="academy-course-grid">{featured.map((c,i)=><Link key={c.code} href={`/academy/catalogue?course=${c.code}`} className="academy-course" data-reveal><div><span>{c.code}</span><ArrowUpRight size={20}/></div><div className="course-thumbnail" style={{backgroundImage:`url('${["/brand/system-academy.webp","/brand/collaboration.jpg","/brand/projects.jpg","/brand/strategy.jpg","/brand/reception.jpg","/brand/studio.jpg","/brand/story-studio-ai.webp"][i]}')`}} aria-hidden="true"/><h3>{c.title}</h3><p>{c.family} · {c.level} · {c.hours} proposed hours</p><small>{c.maturity}</small></Link>)}</div></div></section>
    <section className="feature-section"><div className="feature-photo academy-feature-photo" role="img" aria-label="DigitalBurj Academy coding workshop"/><div className="feature-copy"><span className="eyebrow eyebrow-light">03 / Your workspace</span><h2>Keep the work <span className="serif-accent">that matters.</span></h2><p>Save a course, write a practice draft and reflect on what you learned in your private Academy workspace.</p><Link href="/workspace/academy" className="btn btn-red">Open my learning <ArrowUpRight size={18}/></Link></div></section><SiteFooter/></main>;
}
