import Link from "next/link";
import { and, asc, eq, isNull } from "drizzle-orm";
import { notFound } from "next/navigation";
import { getDb } from "../../../../db";
import { engagements, engagementEntries, engagementEvents, enquiries } from "../../../../db/schema";
import { engagementKinds } from "../../../../lib/engagement-workflow";
import { workspaceContext } from "../../access";
import { addEngagementEntry, requestDiscovery } from "../actions";

export const dynamic = "force-dynamic";
export default async function EngagementDetail({ params }: { params: Promise<{ id: string }> }) {
  const ctx = await workspaceContext(); const { id } = await params;
  const db = getDb();
  const item = await db.select().from(engagements).where(and(eq(engagements.id, id), ctx.orgId ? eq(engagements.orgId, ctx.orgId) : and(eq(engagements.ownerId, ctx.user.userId), isNull(engagements.orgId)))).get();
  if (!item || !["studio", "business"].includes(item.service)) notFound();
  const [entries, events, enquiry] = await Promise.all([
    db.select().from(engagementEntries).where(eq(engagementEntries.engagementId, item.id)).orderBy(asc(engagementEntries.createdAt)),
    db.select().from(engagementEvents).where(eq(engagementEvents.engagementId, item.id)).orderBy(asc(engagementEvents.createdAt)),
    db.select().from(enquiries).where(eq(enquiries.id, item.enquiryId)).get(),
  ]);
  const studio = item.service === "studio"; const canEdit = ctx.role !== "guest" && item.stage === "Draft";
  const kinds = engagementKinds[item.service as keyof typeof engagementKinds];
  return <main className="min-h-screen bg-[#f1f5f7] text-[#102b4c]"><header className="bg-[#102b4c] px-6 py-6 text-white"><div className="mx-auto max-w-6xl"><Link href={`/workspace/engagements?service=${item.service}`} className="text-sm font-bold text-[#9ce2ea]">← {studio ? "Studio" : "Business AI"} briefs</Link><p className="mt-6 text-xs font-bold uppercase tracking-[.15em] text-[#9ce2ea]">{studio ? "Product discovery" : "Operational diagnosis"} / {item.stage}</p><h1 className="mt-2 text-4xl font-bold tracking-[-.055em]">{item.title}</h1><p className="mt-3 max-w-3xl text-[#cbd9e3]">{enquiry?.problem}</p></div></header>
    <div className="mx-auto grid max-w-6xl gap-7 px-6 py-10 lg:grid-cols-[minmax(0,1.5fr)_minmax(270px,.7fr)]"><div><section className="grid gap-3 sm:grid-cols-3">{(studio ? [["Stage",item.stage],["Discovery entries",String(entries.length)],["Decision","Not assessed"]] : [["Stage",item.stage],["Recorded items",String(entries.length)],["Automation","Not approved"]]).map(([label,value]) => <div key={label} className="rounded-2xl border border-[#d7e2ea] bg-white p-5"><p className="text-xs font-bold uppercase tracking-[.14em] text-[#a72436]">{label}</p><p className="mt-3 text-lg font-bold">{value}</p></div>)}</section>
      {canEdit && <section className="mt-7 rounded-2xl border border-[#d7e2ea] bg-white p-6"><h2 className="text-2xl font-bold">Add {studio ? "discovery" : "diagnosis"} detail</h2><p className="mt-2 text-sm text-[#536a7b]">Record what you know and separate evidence from assumptions. The working brief stays private to this workspace.</p><form action={addEngagementEntry} className="mt-6 grid gap-4"><input type="hidden" name="engagementId" value={item.id}/><label className="text-sm font-bold">Entry type<select name="kind" required className="mt-2 block w-full rounded-xl border border-[#bdccd7] bg-white p-3 font-normal">{kinds.map(kind => <option key={kind} value={kind}>{kind}</option>)}</select></label><label className="text-sm font-bold">Title<input name="title" required minLength={3} maxLength={140} className="mt-2 block w-full rounded-xl border border-[#bdccd7] p-3 font-normal"/></label><label className="text-sm font-bold">Details<textarea name="detail" required minLength={15} maxLength={4000} rows={4} className="mt-2 block w-full rounded-xl border border-[#bdccd7] p-3 font-normal" placeholder={studio ? "Who needs this, what is uncertain and what would success look like?" : "What happens now, where is the friction and who owns the process?"}/></label><label className="text-sm font-bold">Evidence or source (optional unless the baseline is measured)<textarea name="evidence" maxLength={800} rows={2} className="mt-2 block w-full rounded-xl border border-[#bdccd7] p-3 font-normal"/></label>{!studio && <fieldset className="grid gap-4 rounded-xl border border-[#d7e2ea] p-4"><legend className="px-2 text-sm font-bold">For baseline entries only</legend><label className="text-sm font-bold">Value and unit<input name="measurement" maxLength={120} placeholder="For example: 12 hours per week" className="mt-2 block w-full rounded-xl border border-[#bdccd7] p-3 font-normal"/></label><label className="text-sm font-bold">Basis<select name="measurementBasis" className="mt-2 block w-full rounded-xl border border-[#bdccd7] bg-white p-3 font-normal"><option value="">Not a baseline</option><option value="Measured">Measured, with source above</option><option value="Estimated">Estimated</option></select></label></fieldset>}<button className="w-fit rounded-full bg-[#102b4c] px-6 py-3 font-bold text-white">Save entry</button></form></section>}
      <section className="mt-7"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-[#ae2335]">Working record</p><h2 className="mt-2 text-2xl font-bold">{studio ? "Discovery and validation" : "Diagnosis and baselines"}</h2></div><span className="text-sm text-[#657789]">{entries.length} entries</span></div>{entries.length ? <div className="mt-5 grid gap-4">{entries.map(entry => <article key={entry.id} className="rounded-2xl border border-[#d7e2ea] bg-white p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-[#b22135]">{entry.kind}</p><h3 className="mt-2 text-xl font-bold">{entry.title}</h3></div><span className="text-xs text-[#657789]">{entry.createdAt.toLocaleDateString("en-AE")}</span></div><p className="mt-3 whitespace-pre-wrap leading-7 text-[#486074]">{entry.detail}</p>{entry.measurement && <p className="mt-4 inline-block rounded-full bg-[#e4f1f3] px-3 py-1 text-sm font-bold text-[#14556a]">{entry.measurementBasis}: {entry.measurement}</p>}{entry.evidence && <p className="mt-3 border-l-2 border-[#21aeb6] pl-4 text-sm text-[#5b7080]">Source: {entry.evidence}</p>}</article>)}</div> : <p className="mt-5 rounded-2xl border border-dashed border-[#b8c9d5] bg-white p-8 text-[#526a7d]">No entries yet. Add a clear problem or current process first.</p>}</section></div>
      <aside className="h-fit space-y-5"><section className="rounded-2xl border border-[#d7e2ea] bg-white p-6"><h2 className="text-xl font-bold">Next step</h2><p className="mt-3 text-sm leading-6 text-[#526a7d]">{item.stage === "Draft" ? "Add your information, then request a discovery conversation. Submission is not approval, a quotation or a commitment to deliver." : "Discovery has been requested. Your brief is read-only to preserve what you sent; the team must review it separately."}</p>{canEdit && <form action={requestDiscovery} className="mt-5"><input type="hidden" name="engagementId" value={item.id}/><button disabled={!entries.length} className="rounded-full bg-[#d20e22] px-5 py-3 text-sm font-bold text-white disabled:cursor-not-allowed disabled:opacity-50">Request discovery ↗</button></form>}</section><section className="rounded-2xl border border-[#d7e2ea] bg-white p-6"><h2 className="text-xl font-bold">History</h2><ol className="mt-4 grid gap-4 border-l-2 border-[#d7e2ea] pl-4">{events.map(event => <li key={event.id}><p className="text-sm font-bold">{event.action.replaceAll(".", " ")}</p><p className="text-xs text-[#657789]">{event.createdAt.toLocaleString("en-AE")}</p></li>)}</ol></section><Link href="/workspace/files" className="block rounded-2xl border border-[#d7e2ea] bg-[#e9f2f5] p-5 text-sm font-bold text-[#113a55]">Private workspace files ↗</Link></aside></div></main>;
}
